"""Declarative base and shared column mixins."""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import DateTime, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Common declarative base for all models."""


def uuid_pk(*, db_generated: bool = False) -> Mapped[uuid.UUID]:
    """A UUID primary key, generated by the application.

    `db_generated=True` additionally declares `DEFAULT gen_random_uuid()`. It is not the default
    because the baseline tables were created without one, and a database built from the models
    would then disagree with every database built by replaying the migrations. Tables whose own
    migration declares the server default pass it here so both paths produce the same DDL —
    `tests/integration/test_migrations.py` is what notices when they stop agreeing.
    """
    if db_generated:
        return mapped_column(primary_key=True, default=uuid.uuid4,
                             server_default=text("gen_random_uuid()"))
    return mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """created_at / updated_at (UTC) on every table."""

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
