"""Render a professional HTML security report from a report + its findings."""

from __future__ import annotations

import html

_SEV_COLOR = {
    "critical": "#b00020",
    "high": "#d9534f",
    "medium": "#f0ad4e",
    "low": "#5bc0de",
    "info": "#777",
}


def _esc(v) -> str:  # noqa: ANN001
    return html.escape(str(v if v is not None else ""))


def render_html(report, findings: list) -> str:  # noqa: ANN001
    summary = report.summary or {}
    counts = summary.get("severity_counts", {})
    score = summary.get("security_score", "n/a")
    posture = summary.get("posture", "")

    rows = []
    for f in sorted(findings, key=lambda x: -x.risk_score):
        color = _SEV_COLOR.get(f.severity, "#777")
        evidence = _esc((f.evidence or {}).get("match") or (f.evidence or {}).get("summary") or "")
        remediation = ""
        if isinstance(f.remediation, dict):
            remediation = _esc(
                f.remediation.get("remediation") or f.remediation.get("summary") or ""
            )
        sev_cell = (
            f"<span style='color:{color};font-weight:600'>{_esc(f.severity.upper())}</span>"
        )
        rows.append(
            f"<tr>"
            f"<td>{sev_cell}</td>"
            f"<td>{f.risk_score}</td>"
            f"<td>{_esc(f.title)}</td>"
            f"<td>{_esc(f.cwe_id)} {_esc(f.owasp_ref)}</td>"
            f"<td><code>{evidence}</code></td>"
            f"<td>{_esc(f.ai_explanation or f.description)}</td>"
            f"<td>{remediation}</td>"
            f"</tr>"
        )

    badges = " ".join(
        f"<span style='background:{_SEV_COLOR[s]};color:#fff;padding:2px 8px;"
        f"border-radius:10px;margin-right:6px'>{s}: {counts.get(s, 0)}</span>"
        for s in ("critical", "high", "medium", "low", "info")
    )
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Security Assessment Report</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:40px;color:#1a1a1a}}
 h1{{border-bottom:3px solid #1a1a1a;padding-bottom:8px}}
 .score{{font-size:48px;font-weight:700}}
 table{{border-collapse:collapse;width:100%;margin-top:16px;font-size:13px}}
 th,td{{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}}
 th{{background:#f4f4f4}}
 code{{background:#f6f6f6;padding:1px 4px}}
</style></head><body>
<h1>Security Assessment Report</h1>
<p><strong>{_esc(report.title)}</strong> — status: {_esc(report.status)}</p>
<h2>Executive Summary</h2>
<p class="score">{_esc(score)}/100 <small>({_esc(posture)})</small></p>
<p>{badges}</p>
<p>{_esc(summary.get("recommendation", ""))}</p>
<h2>Findings</h2>
<table>
<thead><tr><th>Severity</th><th>Risk</th><th>Title</th><th>Standards</th>
<th>Evidence</th><th>Analysis</th><th>Remediation</th></tr></thead>
<tbody>{"".join(rows) or "<tr><td colspan=7>No findings.</td></tr>"}</tbody>
</table>
<p style="margin-top:24px;color:#777;font-size:12px">
Generated by Security Guardian Platform. Severities and risk scores are produced by a deterministic
risk engine; narrative is AI-assisted and human-reviewed.</p>
</body></html>"""
